---
title: "OCR_v2"
author: "Adam Kaderabek"
date: "12/29/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(image.binarization)
library(magick)
library(stringi)
library(stringr)
library(tesseract)
library(tictoc)
library(tidyr)
library(xlsx)
```

# Data Parsing

```{r}
# load garbage line-control regex
load("Dictionary Data/dict_garbage_line_FAFH.RData")
# load in-line garbage control regex
load("Dictionary Data/dict_garbage_inline_FAFH.RData")
# List of total indicators
load("Dictionary Data/dict_total_indicators_FAFH.RData")
# load subtotal indicators
load("Dictionary Data/dict_subtot_indicators_FAFH.RData")
# load tax indicators
load("Dictionary Data/dict_tax_indicators_FAFH.RData")

FAFH4OCR<-paste("K:/Research/Umich_West/2020 Receipt Validation/TesseractOCR/04 FAFH Processed/FAFH Ready/", 
               list.files("K:/Research/Umich_West/2020 Receipt Validation/TesseractOCR/04 FAFH Processed/FAFH Ready/"), sep="")

FAFH.OCROut<-paste("K:/Research/Umich_West/2020 Receipt Validation/TesseractOCR/04 FAFH Processed/Processed/Second Pass/", 
                  list.files("K:/Research/Umich_West/2020 Receipt Validation/TesseractOCR/04 FAFH Processed/FAFH Ready/"), sep="")
FAFH.OCROut<-str_replace(FAFH.OCROut, ".jpg|.JPG|.png|.PNG", ".xlsx")

```


```{r}
# i<-11

for (i in 1:length(FAFH4OCR)) { # for each receipt image in folder
  tic("start")
  # import image file i
  image.scan<-image_read(FAFH4OCR[i])
  # scan image file i
  image.text<-image_ocr(image.scan)
  # un-list image text by line
  image.lines<-data.frame(EventID=str_extract(FAFH4OCR[i], "[0-9]+(?=_)"), 
                          OLID=1:length(unlist(str_split(image.text, "\n"))),
                          OCRLines=unlist(str_split(image.text, "\n")))
  # Convert all characters to UPPER case
  image.lines$OCRLines2<-str_to_upper(image.lines$OCRLines)
 
   # replace any commas (,) as period/decimal point (.)
  image.lines$OCRLines2<-str_replace_all(image.lines$OCRLines2, pattern = ",", replacement = ".")
  
  # remove garbage regex patterns from line (before special characters in order to get dates and times removed)
  image.lines$OCRLines2<-str_replace_all(image.lines$OCRLines2, pattern = regex(paste(garbageregex, collapse = "|")), replacement = "")
  
  # remove all special characters except (, ), ., /, and @
  image.lines$OCRLines2<-str_remove_all(image.lines$OCRLines2, regex("[^A-Z0-9\\s\\.@/)(]"))
  
  # replace duplicated white spaces with a single space
  image.lines$OCRLines2<-str_replace_all(image.lines$OCRLines2, "\\s{2,}", " ") 
  
  # remove spaces from start or end of string
  image.lines$OCRLines2<-str_remove(image.lines$OCRLines2, "^\\s+|\\s+$")
  
  # identify garbage lines and replace as empty line[l]
  image.lines$OCRLines2<-ifelse(str_detect(image.lines$OCRLines2, regex(paste(garbageline, collapse = "|")))==TRUE, "", image.lines$OCRLines2)
  
  # create quantity indicator
  image.lines$isQuantity<-ifelse(str_detect(image.lines$OCRLines2, regex("@"))==TRUE, 1 ,0)
  
  # create discount indicator
  image.lines$isDiscount<-ifelse(str_detect(image.lines$OCRLines2, regex("DISC|MANAGER"))==TRUE, 1 ,0)
  
  # extract price patterns
  # image.lines$amount<-str_extract(image.lines$OCRLines2, "(?<=\\s?)\\d{0,2}\\s?\\.\\d{2}$|\\d{0,2}\\s*\\.\\d{2}$(?=.{0,1})")
  image.lines$amount<-str_extract(image.lines$OCRLines2, "[0-9\\.\\s]{3,8}$")
  
  # remove price patterns
  image.lines$OCRLines2<-ifelse(image.lines$isQuantity==0, 
                                str_remove(image.lines$OCRLines2, "(?<=\\s?)\\d{0,3}\\s?\\.\\d+$|\\d{0,3}\\s*\\.\\d+$(?=.{0,1})"), image.lines$OCRLines2)
  # remove spaces from prices
  image.lines$amount<-str_remove(image.lines$amount, "\\s")
  
  # create "TAX" descriptor
  image.lines$OCRLines2<-ifelse(str_detect(image.lines$OCRLines2, regex(paste(tax.indicators, collapse = "|")))==TRUE, "TAX", image.lines$OCRLines2)
  # create subtotal descriptor
  image.lines$OCRLines2<-ifelse(str_detect(image.lines$OCRLines2, regex(paste(subtotal.indicators, collapse = "|")))==TRUE, "SUBTOTAL", image.lines$OCRLines2)
  # create "TOTAL" descriptor
  image.lines$OCRLines2<-ifelse(str_detect(image.lines$OCRLines2, regex(paste(total.indicators, collapse = "|")))==TRUE, "TOTAL", image.lines$OCRLines2)
  
  
  # create subtotal indicator
  image.lines$isSubtotal<-ifelse(str_detect(image.lines$OCRLines2, "SUBTOTAL")==TRUE & !is.na(image.lines$amount), 1, 0)
  # create "TAX" indicator
  image.lines$isTax<-ifelse(str_detect(image.lines$OCRLines2, "TAX")==TRUE & !is.na(image.lines$amount), 1, 0)
  # create "TOTAL" indicator
  image.lines$isRecTotal<-ifelse(str_detect(image.lines$OCRLines2, "(?<!.)TOTAL")==TRUE & !is.na(image.lines$amount), 1 ,0)
  
  # replace whitespace lines with NA
  image.lines$OCRLines2<-str_replace(image.lines$OCRLines2, "^\\s*$", "NA")
  image.lines$OCRLines2<-ifelse(image.lines$OCRLines2=="NA", NA, image.lines$OCRLines2)
  
  # subset rows to only those with data other than item name
  receipt_df<-subset(image.lines, !is.na(OCRLines2)); receipt_df
  receipt_df$OLID<-seq(1:nrow(receipt_df))
  
  receipt_df<-receipt_df %>%
    select(EventID, OLID, OCRLines, OCRLines2, amount, isQuantity, isDiscount, isSubtotal, isTax, isRecTotal)
  
  # write out xlsx/csv
  write.xlsx(receipt_df, file = FAFH.OCROut[i], row.names = FALSE)
  # write.csv(receipt, file = FAFH.OCROut[i], row.names = FALSE)
  print(receipt_df)
  toc()
}


```

## Regex Testing
```{r}
strings<-c("TS SWEET 001800042742 F =—s_- 3.87 0", "-1.00", "1.00-", "- 1.00", "- .56", "1.25 -", ".25 -", "BREAD 007874298199 F = =—ss« 1.00 0", "GOLDEN GRHM 001600027516 F 2.98 0", "2.02 lb @ 1 lb /0.62 1.05 N", "1 @ 2/6.00 N ", "1@2/6.00", "8463841384618 2.8/3" )

str_view_all(image.lines$OCRLines2, "^\\s+$")


regex("[^A-Za-z0-9$\\s\\.@/-]|-(?=[^A-Za-z0-9\\s])|(?<=[^A-Za-z0-9\\s])-\\s|(?<!@.{1,9})/", ignore_case = TRUE)# remove special characters with hyphens unless they are close to a number. Keep "/" if line contains preceding "@"
```




